# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tbd < Formula
  desc "A sweet and speedy code generator for dbt."
  homepage "https://github.com/gwenwindflower/tbd"
  version "0.0.9"
  license "GPL-3.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/gwenwindflower/tbd/releases/download/v0.0.9/tbd_Darwin_x86_64.tar.gz"
    sha256 "43c59976dfac52f3fde976a87d86c4b94511084e8d1a133457be87f8c8b6ecd1"

    def install
      bin.install "tbd"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/gwenwindflower/tbd/releases/download/v0.0.9/tbd_Darwin_arm64.tar.gz"
    sha256 "0ae97a5308c8d3305d4da38cc1dc49eeb3b097b1f32a2e9ab4feba9f4063b2cf"

    def install
      bin.install "tbd"
    end
  end
end
