# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tbd < Formula
  desc "A sweet and speedy code generator for dbt."
  homepage "https://github.com/gwenwindflower/tbd"
  version "0.0.18"
  license "GPL-3.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/gwenwindflower/tbd/releases/download/v0.0.18/tbd_Darwin_x86_64.tar.gz"
    sha256 "da87ea1c2aff8360dd2033e7f80bc5256a12774c646faa0d27a48ad7e3e2a826"

    def install
      bin.install "tbd"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/gwenwindflower/tbd/releases/download/v0.0.18/tbd_Darwin_arm64.tar.gz"
    sha256 "0d70b9e905f8a3626a6d50d53e39810b65d74711d96eb96405f2ba8958754441"

    def install
      bin.install "tbd"
    end
  end
end
